var GAME_LEVELS = [

  ["                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "              oo                                                   P                        ",
   "              oo                                                                            ",
   "              oo                                                xxxxxx                      ",
   "                                                   x      xx    xvvxvx                      ",
   "                                          xx                                                ",
   "                                                                                            ",
   "                                                                                            ",
   "                                     ooo                                    xx              ",
   "                                                                             x              ",
   "                                                                            x               ",
   "                                   x     x                         ooo                 x    ",
   "             ^^^^                                                            x              ",
   "     @       x  x                     |                                                 x   ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x  |         |   x                 x     x                    ",
   "                              x!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxx                  xxxxxxx                    ",
   "                                                                                            ",
   "                                                                                            "],
  ["                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                       o                                                            o                                         ",
   "                                                                                                                                                                                                                              ",
   "                                                                     o                                                                                                                                                        ",
   "                                                                                                                                                                                                                              ",
   "                                                                                                                                                                                                                o             ",
   "                                                                                                                                          oo                                                                    o             ",
   "                                                                                           =                           ^          xxx    x^^x                                                         xx        o             ",
   "                       o                                                                xxxxxxxxx   xxx^                                                                                             xxx        o             ",
   "                                                                                                                                                                                                    xxxx        o             ",
   "                                                                     ^                                 o                                                                                           xxxxx        o             ",
   "                 x   x^x^x                        xx          PP                     x^x               x     x^     ^  ^  ^     x         xx      x  x          xx   x            xx^x            xxxxxx        o    xxxx     ",
   "                                         xx       xx          xx                                                                                 xx  xx        xxx   xx                          xxxxxxx        o   xxxxxx    ",
   "                               xx        xx       xx          xx                                                                                xxx  xxx      xxxx   xxx     xx              xx xxxxxxxx        o   xxxxxx    ",
   "    @                   =      xx        xx =     xx    = =   xx                                          =        =                       =   xxxx  xxxx    xxxxx   xxxx    xx              xxxxxxxxxxx        ^   xxxxxx    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                         x    x              x    x                                                              x   x                                                        ",
   "                                                                         x!!!!x              x!!!!x                                                              x!!!x                                                        "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                       o                                                        ",
   "                                                                                ",
   "                                      xxxxxxxxx                                 ",
   "                                      x       x                                 ",
   "                                      x       x                                 ",
   "                                      x       x                                 ",
   "                                      x       x                   P             ",
   "                                      x       x                                 ",
   "                                              x                           ooo   ",
   "                                            o x                         xxxxxxxx",
   "                                   x  xx    o x                   |     xxxxxxxx",
   "                  x!!!!!!!!!x         x     o x                      xxxxxxxxxxx",
   "                                      x   ! o x                                 ",
   "                                      x       x     o     xxxxxx                ",
   "                                      x       x     xx      xx    xx!xx         ",
   "                                 xxxx x   o   x                  x!!!x          ",
   "                                      x   o   x                                 ",
   "                                      x       x     xxxxxx                      ",
   "            o      o      o           x o     x                                 ",
   "         xxxxxxxxxxxxxxxxxxxx         x o !   x             x   xxxxxxx         ",
   "                                      x o     x                                 ",
   "                                     xx       x                             xxxx",
   "                                     xx       x                    o            ",
   " @                                xxx x                          xxxxx          ",
   "xxxx^^^                         xx    x                  xxxxxxxxx   xxxxxxxxx  ",
   "      x                        x      xxx^^^xxxxxxxxx |                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                                                                  ",
   "                                     o                                                                                                                            ",
   "                                                                                                                                                                  ",
   "                                                                               o                                                                                  ",
   "                                                                               o                                                                                  ",
   "                                                                               o                                                                                  ",
   "                        ooo                                                                                                                                       ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                      o                                                           ",
   "                                                       ^                                                                                                          ",
   "                                 o                                                                                                                                ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                    o             ",
   "                                     ^                                                                                                                            ",
   "                                            o                                                                                                                     ",
   "         o                                                                                                    ^                                                   ",
   "                                                                                                                                                                  ",
   "                  ^                                                              |                                                                                ",
   "                                                                                                                                                                  ",
   "                                                                        ^                                                                                         ",
   "                                                                                                                                                                  ",
   "                                                                                                 ^                                                                ",
   "                                                                                                                                     ^                            ",
   "                                   ^                                                                                                                              ",
   "                                                     |                                                                                                            ",
   "                                                                                                        |                        |                                ",
   " @                                                                |                                                                                               ",
   "xxxxx^^^                |                     ^                                                                     |                                    |        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                              ",
   "          x   x     xxx     x   x             ",
   "          x   x    x   x    x   x             ",
   "          xxxxx    x   x    x   x             ",
   "            x      x   x    x   x             ",
   "            x       xxx      xxx              ",
   "                                              ",
   "                                              ",
   "                     @                        ",
   "        x     x     xxx    xx    x   x        ",
   "        x     x      x     x x   x   x        ",
   "        x  x  x      x     x  x  x   x        ",
   "        x  x  x      x     x   x x            ",
   "         xx xx      xxx    x    xx   x        ",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "                                              "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
